# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170611_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
